name: Reserve a file
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reserve a file'
        default: 'World'
        required: true
jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5

      - name: Reserve a file to translate
        run: |
             ls > list.txt

      - name: Pushing to the protected branch 'protected'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: master

